### ISSUE TITLE
version (1.90; MobDebug 0.706) and Lua 5.4.3

### ISSUE THREAD

**Issue by decuant** [pkulchenko/ZeroBraneStudio#1118]
Hello Paul,

I'm using the standard distribution of ZeroBrane, not this one on GitHub. I have symlinked 5.4.x to your 5.3 dll, and luasocket...

Using Lua 5.4.2 is ok, both in run and in debug.

Version 5.4.3 runs the application properly, but fails to start the debugger, it might be that you already know this issue?

[Error 1.txt](https://github.com/pkulchenko/ZeroBraneStudio/files/6909979/Error.1.txt)

I tried different applications of mine, and I have lost the output when he was mentioning mobdebug, I-m sorry but  I can't reproduce _that_ output.

I will get back to release 5.4.2, since it works properly for the things I'm doing. But I can do testing for you if you need it.

Antonio

**Comment by pkulchenko** [comment]
It looks like the issue that was fixed in pkulchenko/MobDebug#60. Can you retest with the current version of Mobdebug in the IDE (or from the Mobdebug repository) and let me know if this eliminates the issue? Thanks.

**Comment by decuant** [comment]
Hello Paul, thank you for the fast reply.

I tested the new mobdebug on both 32 and 64 bits with lua 543 and it does work as supposed.

Sorry it was my fault, I should have had a look around your repositories, where there's mobdebug stand-alone.

Thank you very much for all your efforts!

Antonio

**Comment by pkulchenko** [comment]
Antonio, just to confirm, upgrading Mobdebug fixed the issue, right?

**Comment by decuant** [comment]
Hi Paul,

yes, I tested on Windows 10 64bits and Windows 8.1 32bits.  I used lua 5.4.3.

May be you missed my previous reply?

I renamed the existing  mobdebug.lua and copied over your new version.

Antonio

**Comment by pkulchenko** [comment]
Got it; thank you!
