### ISSUE TITLE
Sometimes a tab might become unresponsive

### ISSUE THREAD

**Issue by joe528** [pkulchenko/ZeroBraneStudio#444]
Since recently (probably starting from v1.0 or so), I have encountered a few times that a tab becomes unresponsive.
When this happens, if I click the file name of this tab in the file list table, the main editor window will not go to this file either.

Please see this screen recording that shall explain this issue clearly:
http://pagesay.com/tmp/tab_became_unclickable.mov

I am not sure what causes this happen. I just use ZBS normally. No advanced operations, just editing/cmd-S/cmd-F/cmd-shift-F, etc. Sometimes it just happens but it does not happen all the time. I have to restart ZBS in order to open that tab.

**Comment by joe528** [comment]
After I created this bug, I restarted ZBS. And after 5 mins, it happened again. In this 5 minutes, I think I edited some code, searched some keyword in all files, went to couple of files to edit, cmd-s, clicked ">" to  run Corona simulator and when I came back to ZBS and tried to clicked one of the tab (this tab happened to be the same tab in my previous video), this tab is not responsive again.

PS. Actually it's not really "unresponsive", when I clicked this tab, ZBS just goes to the other tab. You should be able to observe this in the screen recording too.

**Comment by pkulchenko** [comment]
@joe528, what version of ZBS are you currently running? Is it v1.0 or are you running some later (development) version? Can you check `git describe` if you are running from a cloned repository?

I have never seen what you describe to happen; there used to be a bug that one of the tabs became unresponsive after dragging tabs around, but that was the only condition when that happened. There was also a recent bug when this was fixed (#427), so I'd be interested if you are running a version before or after commit c383889d.

**Comment by joe528** [comment]
Where/how to run 'git describe'?

I am using v1.0 I downloaded from your website. I usually don't download Zerobrane from github directly except a few times earlier you asked me to check for bug fixing with latest commits but it's a few months ago.

I will try to remove the whole directory and reinstall v1.0 again.

**Comment by pkulchenko** [comment]
> Where/how to run 'git describe'?

@joe528, I thought you used a git repository, but if not, it doesn't apply. Reinstalling is not likely to help as the logic is still the same and ZBS doesn't keep much data around that may affect its launches. I'd be interested to see if you can still reproduce this issue on the latest code.

If you don't mind, you can download the [zip file here](https://github.com/pkulchenko/ZeroBraneStudio/archive/master.zip), unzip it, and run `./zbstudio.sh` from that folder. It should use all your current settings and configuration (if you keep it in user settings: `Edit | Preferences | Settings: User`).

**Comment by pkulchenko** [comment]
@joe528, also, do you have any plugins installed?

**Comment by joe528** [comment]
sure. I will let you know if I see this issue happen again with the latest code.

**Comment by joe528** [comment]
I don't think I have any plugin installed. (I don't even know how)

Here is my preference: (I think they are just themes/colors)

============================

editor.fold = false
editor.fontsize = 22 -- this is mapped to ide.config.editor.fontsize
editor.fontname = "Emilbus Mono"

outputshell.fontname = "Emilbus Mono"
outputshell.fontsize = 16

filetree.fontname = "Arial"
filetree.fontsize = 16

-- to change the default color scheme; check tomorrow.lua for the list
-- of supported schemes or use cfg/scheme-picker.lua to pick a scheme.
local G = ...
styles = G.loadfile('cfg/tomorrow.lua')('Monokai')
-- also apply the same scheme to Output and Console windows
stylesoutshell = styles

styles.auxwindow = styles.text -- apply text colors to auxiliary windows
styles.calltip = styles.text -- apply text colors to tooltips 

editor.tabwidth = 4

editor.usewrap = false

singleinstance = false

**Comment by joe528** [comment]
@pkulchenko Now I am using the latest version as you suggested... I have a question unrelated to this issue though... now when I "search in all files", the result forms a new tab "Search Result" in main editing window... is there any configuration that I can go back to the original behavior (just showing the results in the output window)?

**Comment by pkulchenko** [comment]
@joe528, Thank you for the feedback; I responded in #416, which tracks and discusses search-related changes.

**Comment by pkulchenko** [comment]
@joe528, closing this as I expect it to be fixed by #427. Please reopen if the issue still happens on the current master.

**Comment by srdjan-m** [comment]
I am experiencing the same issue with tabs. The problem started about the same time as joe528 reported it but I never had a free time to report it :-)
It is not a big issue because I can "unlock" the unresponsive tab by dragging other tabs around. But, yes, it is annoying and it is still here (v1.10).

**Comment by pkulchenko** [comment]
@srdjan-m, does it happen after "tab move" with a mouse? I've seen this happening and it appears to be a wxwidgets problem. I can't find the ticket at the moment, but this one looks like the closest: http://trac.wxwidgets.org/ticket/16605

All other related issues discussed in this ticket should be fixed.

**Comment by srdjan-m** [comment]
I still can't find a way how to reproduce it. I think that it appears after tabs have been repositioned. By clicking the unresponsive tab the editor's focus always jumps to one specific tab.
It looks like the bug you mentioned above...
